apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chainlink-package
  description: Kurtosis package for Chainlink oracles
  annotations:
    github.com/project-slug: LZeroAnalytics/chainlink-package
    backstage.io/view-url:    https://github.com/LZeroAnalytics/chainlink-package
    backstage.io/techdocs-ref: url:https://github.com/LZeroAnalytics/chainlink-package/blob/master/README.md
spec:
  type: Oracle
  lifecycle: production
  owner: bloctopus